version: "3.9"
name: bgcv
services:
  nginx:
    container_name: bgcv_nginx
    image: nginx:latest
    volumes:
      - ./conf/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    links:
      - node

  node:
    platform: "linux/x86_64"
    build:
      context: ../..
      args: [ "NODE_ENV=development" ]
    volumes:
      # Mount volumes of generated files directories.
      - ../../app/resources/public/pdf:/usr/src/bgcv/app/resources/public/pdf
    environment:
      - PORT=8080
