version: "3.9"
name: bgcv
services:
  nginx:
    container_name: bgcv_nginx
    image: nginx:latest
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=bgcv-node
      - NGINX_PORT=80
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "bgcv-node:host-gateway"

  node:
    platform: "linux/x86_64"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args: [ "NODE_ENV=development" ]
    volumes:
      # Mount volumes of generated files directories.
      - ../app/resources/public/pdf:/usr/src/bgcv/app/resources/public/pdf
    environment:
      - COMPOSE_PROJECT_NAME=bgcv
      - PORT=8080
    ports:
      - "8080:8080"
    links:
      - nginx
