version: "3.9"
services:
  bgcv-node:
    platform: "linux/x86_64"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      # Mount volumes of generated files directories.
      - ../app/resources/public/css:/usr/src/bgcv/app/resources/public/css
      - ../app/resources/public/pdf:/usr/src/bgcv/app/resources/public/pdf
    environment:
      COMPOSE_PROJECT_NAME: bgcv
      NODE_ENV: dev
      PORT: 8080
    ports:
      - "8080:8080"
