version: "3.9"
services:
  nginx:
    container_name: bgcv-nginx
    image: ghcr.io/bguina/bgcv-nginx:latest
    volumes:
      - /home/debian/certs/bguina.dev:/root/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - node-production

  node-production:
    container_name: bgcv-node
    image: ghcr.io/bguina/bgcv-node:latest
    environment:
      NODE_ENV: "production"
      PORT: 8080
