version: "3.9"
services:
  node-production:
    image: ghcr.io/bguina/bgcv-node:latest
    volumes:
      # Mount volume of certs.
      - ../certs:/usr/src/bgcv/app/certs
    environment:
      PORT: 8080
    ports:
      - "443:8080"
