version: "3.9"
services:
  bgcv:
    container_name: bgcv
    image: ghcr.io/bguina/bgcv:latest
    volumes:
      # Mount volumes of generated files directories.
      - ../resources/public/css:/usr/src/bgcv/app/resources/public/css
      - ../resources/public/pdf:/usr/src/bgcv/app/resources/public/pdf
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
