name: Deploy
on: workflow_dispatch

jobs:
  deploy-bgcv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy deployment script and configuration files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: bguina.dev
          username: ${{ secrets.SSH_USERNAME }}
          key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy/deploy.sh,deploy/docker-compose.yml"
          target: "/home/${{ secrets.SSH_USERNAME }}"

      - name: Execute deployment script
        uses: appleboy/ssh-action@v1.0.0
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: bguina.dev
          username: ${{ secrets.SSH_USERNAME }}
          key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_ACTOR, GITHUB_TOKEN
          script: bash -e /home/${{ secrets.SSH_USERNAME }}/deploy/deploy.sh
